// ========================================
// GAME DATA - Planets, Stages, Pets
// ========================================

// Pet Types
const PET_TYPES = {
    FIRE: 'fire',
    WATER: 'water',
    EARTH: 'earth',
    AIR: 'air',
    LIGHT: 'light',
    DARK: 'dark',
};

// Planets Configuration
const PLANETS = [
    {
        id: 'earth',
        name: 'Trái Đất',
        emoji: '🌍',
        description: 'Hành tinh xanh với nhiều sinh vật đa dạng',
        unlocked: true,
        color: '#4CAF50',
    },
    {
        id: 'mars',
        name: 'Sao Hỏa',
        emoji: '🔴',
        description: 'Hành tinh đỏ với sinh vật lửa mạnh mẽ',
        unlocked: false,
        unlockRequirement: 5, // Cần hoàn thành 5 mốc
        color: '#f44336',
    },
    {
        id: 'neptune',
        name: 'Sao Hải Vương',
        emoji: '💙',
        description: 'Hành tinh nước với sinh vật biển huyền bí',
        unlocked: false,
        unlockRequirement: 10,
        color: '#2196F3',
    },
    {
        id: 'jupiter',
        name: 'Sao Mộc',
        emoji: '🟠',
        description: 'Hành tinh khổng lồ với sinh vật gió mạnh mẽ',
        unlocked: false,
        unlockRequirement: 15,
        color: '#FF9800',
    },
    {
        id: 'moon',
        name: 'Mặt Trăng',
        emoji: '🌙',
        description: 'Vệ tinh bí ẩn với sinh vật ánh sáng',
        unlocked: false,
        unlockRequirement: 20,
        color: '#9C27B0',
    },
];

// Stages for each planet
const STAGES = {
    earth: [
        { id: 'earth_1', name: 'Slime', emoji: '🟢', hp: 80, atk: 8, petId: 'slime', reward: 50, exp: 40, type: PET_TYPES.EARTH, materials: ['slime_gel'] },
        { id: 'earth_2', name: 'Rabbit', emoji: '🐰', hp: 100, atk: 10, petId: 'rabbit', reward: 60, exp: 50, type: PET_TYPES.EARTH, materials: ['rabbit_fur'] },
        { id: 'earth_3', name: 'Wolf', emoji: '🐺', hp: 120, atk: 12, petId: 'wolf', reward: 75, exp: 60, type: PET_TYPES.EARTH, materials: ['wolf_fang'] },
        { id: 'earth_4', name: 'Bear', emoji: '🐻', hp: 150, atk: 15, petId: 'bear', reward: 90, exp: 70, type: PET_TYPES.EARTH, materials: ['bear_claw'] },
        { id: 'earth_5', name: 'Golem', emoji: '🪨', hp: 180, atk: 18, petId: 'golem', reward: 100, exp: 80, type: PET_TYPES.EARTH, materials: ['golem_core'] },
    ],
    mars: [
        { id: 'mars_1', name: 'Fire Sprite', emoji: '🔥', hp: 140, atk: 16, petId: 'fire_sprite', reward: 110, exp: 90, type: PET_TYPES.FIRE, materials: ['fire_essence'] },
        { id: 'mars_2', name: 'Lava Beast', emoji: '🌋', hp: 170, atk: 19, petId: 'lava_beast', reward: 130, exp: 100, type: PET_TYPES.FIRE, materials: ['lava_stone'] },
        { id: 'mars_3', name: 'Phoenix', emoji: '🦅', hp: 200, atk: 22, petId: 'phoenix', reward: 150, exp: 120, type: PET_TYPES.FIRE, materials: ['phoenix_feather'] },
        { id: 'mars_4', name: 'Inferno Dragon', emoji: '🐉', hp: 250, atk: 25, petId: 'inferno_dragon', reward: 180, exp: 140, type: PET_TYPES.FIRE, materials: ['dragon_scale'] },
        { id: 'mars_5', name: 'Flame Titan', emoji: '👹', hp: 300, atk: 28, petId: 'flame_titan', reward: 200, exp: 160, type: PET_TYPES.FIRE, materials: ['titan_heart'] },
    ],
    neptune: [
        { id: 'neptune_1', name: 'Jellyfish', emoji: '🪼', hp: 160, atk: 18, petId: 'jellyfish', reward: 120, exp: 95, type: PET_TYPES.WATER, materials: ['jelly_essence'] },
        { id: 'neptune_2', name: 'Shark', emoji: '🦈', hp: 190, atk: 21, petId: 'shark', reward: 140, exp: 110, type: PET_TYPES.WATER, materials: ['shark_tooth'] },
        { id: 'neptune_3', name: 'Kraken', emoji: '🦑', hp: 220, atk: 24, petId: 'kraken', reward: 160, exp: 130, type: PET_TYPES.WATER, materials: ['kraken_tentacle'] },
        { id: 'neptune_4', name: 'Sea Serpent', emoji: '🐍', hp: 260, atk: 27, petId: 'sea_serpent', reward: 190, exp: 150, type: PET_TYPES.WATER, materials: ['serpent_scale'] },
        { id: 'neptune_5', name: 'Leviathan', emoji: '🐋', hp: 320, atk: 30, petId: 'leviathan', reward: 220, exp: 170, type: PET_TYPES.WATER, materials: ['leviathan_pearl'] },
    ],
    jupiter: [
        { id: 'jupiter_1', name: 'Wind Spirit', emoji: '💨', hp: 180, atk: 20, petId: 'wind_spirit', reward: 130, exp: 100, type: PET_TYPES.AIR, materials: ['wind_essence'] },
        { id: 'jupiter_2', name: 'Thunder Bird', emoji: '🦅', hp: 210, atk: 23, petId: 'thunder_bird', reward: 150, exp: 115, type: PET_TYPES.AIR, materials: ['thunder_feather'] },
        { id: 'jupiter_3', name: 'Storm Drake', emoji: '🐲', hp: 240, atk: 26, petId: 'storm_drake', reward: 170, exp: 135, type: PET_TYPES.AIR, materials: ['storm_crystal'] },
        { id: 'jupiter_4', name: 'Cyclone Giant', emoji: '🌪️', hp: 280, atk: 29, petId: 'cyclone_giant', reward: 200, exp: 155, type: PET_TYPES.AIR, materials: ['cyclone_core'] },
        { id: 'jupiter_5', name: 'Sky Titan', emoji: '⚡', hp: 340, atk: 32, petId: 'sky_titan', reward: 230, exp: 180, type: PET_TYPES.AIR, materials: ['titan_essence'] },
    ],
    moon: [
        { id: 'moon_1', name: 'Star Fox', emoji: '🦊', hp: 200, atk: 22, petId: 'star_fox', reward: 140, exp: 105, type: PET_TYPES.LIGHT, materials: ['star_dust'] },
        { id: 'moon_2', name: 'Unicorn', emoji: '🦄', hp: 230, atk: 25, petId: 'unicorn', reward: 160, exp: 120, type: PET_TYPES.LIGHT, materials: ['unicorn_horn'] },
        { id: 'moon_3', name: 'Griffin', emoji: '🦅', hp: 260, atk: 28, petId: 'griffin', reward: 180, exp: 140, type: PET_TYPES.LIGHT, materials: ['griffin_feather'] },
        { id: 'moon_4', name: 'Celestial Dragon', emoji: '🐉', hp: 300, atk: 31, petId: 'celestial_dragon', reward: 210, exp: 160, type: PET_TYPES.LIGHT, materials: ['celestial_scale'] },
        { id: 'moon_5', name: 'Cosmic Entity', emoji: '✨', hp: 360, atk: 35, petId: 'cosmic_entity', reward: 250, exp: 190, type: PET_TYPES.LIGHT, materials: ['cosmic_shard'] },
    ],
};

// Pet Database with detailed stats
const PETS_DATABASE = {
    // Earth Pets
    slime: {
        id: 'slime',
        name: 'Slime',
        emoji: '🟢',
        image: 'assets/pets/slime.png',
        type: PET_TYPES.EARTH,
        baseHp: 50,
        baseAtk: 8,
        baseDef: 5,
        skill: {
            name: 'Bounce Attack',
            emoji: '💚',
            effect: 'dmg',
            power: 25,
            cost: 30,
            description: 'Nhảy lên gây 25 sát thương',
        },
        rarity: 'common',
    },
    rabbit: {
        id: 'rabbit',
        name: 'Rabbit',
        emoji: '🐰',
        type: PET_TYPES.EARTH,
        baseHp: 60,
        baseAtk: 10,
        baseDef: 6,
        skill: {
            name: 'Quick Strike',
            emoji: '⚡',
            effect: 'dmg',
            power: 30,
            cost: 30,
            description: 'Tấn công nhanh gây 30 sát thương',
        },
        rarity: 'common',
    },
    wolf: {
        id: 'wolf',
        name: 'Wolf',
        emoji: '🐺',
        image: 'assets/pets/shadow_wolf.png',
        type: PET_TYPES.EARTH,
        baseHp: 70,
        baseAtk: 12,
        baseDef: 7,
        skill: {
            name: 'Howl',
            emoji: '🌙',
            effect: 'atkBuff',
            power: 20,
            cost: 30,
            description: 'Tăng 20% sát thương',
        },
        rarity: 'uncommon',
    },
    bear: {
        id: 'bear',
        name: 'Bear',
        emoji: '🐻',
        type: PET_TYPES.EARTH,
        baseHp: 90,
        baseAtk: 15,
        baseDef: 10,
        skill: {
            name: 'Bear Hug',
            emoji: '🤗',
            effect: 'dmg',
            power: 35,
            cost: 30,
            description: 'Ôm chặt gây 35 sát thương',
        },
        rarity: 'uncommon',
    },
    golem: {
        id: 'golem',
        name: 'Golem',
        emoji: '🪨',
        image: 'assets/pets/stone_golem.png',
        type: PET_TYPES.EARTH,
        baseHp: 100,
        baseAtk: 18,
        baseDef: 15,
        skill: {
            name: 'Stone Shield',
            emoji: '🛡️',
            effect: 'heal',
            power: 40,
            cost: 30,
            description: 'Hồi 40 HP',
        },
        rarity: 'rare',
    },

    // Fire Pets
    fire_sprite: {
        id: 'fire_sprite',
        name: 'Fire Sprite',
        emoji: '🔥',
        image: 'assets/pets/fire_dragon.png',
        type: PET_TYPES.FIRE,
        baseHp: 65,
        baseAtk: 16,
        baseDef: 6,
        skill: {
            name: 'Flame Burst',
            emoji: '💥',
            effect: 'dmg',
            power: 40,
            cost: 30,
            description: 'Bùng cháy gây 40 sát thương lửa',
        },
        rarity: 'uncommon',
    },
    lava_beast: {
        id: 'lava_beast',
        name: 'Lava Beast',
        emoji: '🌋',
        type: PET_TYPES.FIRE,
        baseHp: 80,
        baseAtk: 19,
        baseDef: 8,
        skill: {
            name: 'Lava Splash',
            emoji: '🌊',
            effect: 'dmg',
            power: 45,
            cost: 30,
            description: 'Phun dung nham gây 45 sát thương',
        },
        rarity: 'rare',
    },
    phoenix: {
        id: 'phoenix',
        name: 'Phoenix',
        emoji: '🦅',
        image: 'assets/pets/phoenix.png',
        type: PET_TYPES.FIRE,
        baseHp: 85,
        baseAtk: 22,
        baseDef: 9,
        skill: {
            name: 'Rebirth',
            emoji: '✨',
            effect: 'heal',
            power: 50,
            cost: 30,
            description: 'Tái sinh hồi 50 HP',
        },
        rarity: 'rare',
    },
    inferno_dragon: {
        id: 'inferno_dragon',
        name: 'Inferno Dragon',
        emoji: '🐉',
        type: PET_TYPES.FIRE,
        baseHp: 110,
        baseAtk: 25,
        baseDef: 12,
        skill: {
            name: 'Fire Breath',
            emoji: '🔥',
            effect: 'dmg',
            power: 55,
            cost: 30,
            description: 'Hơi thở lửa gây 55 sát thương',
        },
        rarity: 'epic',
    },
    flame_titan: {
        id: 'flame_titan',
        name: 'Flame Titan',
        emoji: '👹',
        type: PET_TYPES.FIRE,
        baseHp: 130,
        baseAtk: 28,
        baseDef: 14,
        skill: {
            name: 'Inferno Strike',
            emoji: '⚡',
            effect: 'dmg',
            power: 60,
            cost: 30,
            description: 'Đòn địa ngục gây 60 sát thương',
        },
        rarity: 'legendary',
    },

    // Water Pets
    jellyfish: {
        id: 'jellyfish',
        name: 'Jellyfish',
        emoji: '🪼',
        image: 'assets/pets/water_spirit.png',
        type: PET_TYPES.WATER,
        baseHp: 70,
        baseAtk: 18,
        baseDef: 7,
        skill: {
            name: 'Poison Sting',
            emoji: '☠️',
            effect: 'dmg',
            power: 42,
            cost: 30,
            description: 'Chích độc gây 42 sát thương',
        },
        rarity: 'uncommon',
    },
    shark: {
        id: 'shark',
        name: 'Shark',
        emoji: '🦈',
        image: 'assets/pets/ice_penguin.png',
        type: PET_TYPES.WATER,
        baseHp: 85,
        baseAtk: 21,
        baseDef: 9,
        skill: {
            name: 'Bite',
            emoji: '🦷',
            effect: 'dmg',
            power: 48,
            cost: 30,
            description: 'Cắn mạnh gây 48 sát thương',
        },
        rarity: 'rare',
    },
    kraken: {
        id: 'kraken',
        name: 'Kraken',
        emoji: '🦑',
        type: PET_TYPES.WATER,
        baseHp: 95,
        baseAtk: 24,
        baseDef: 10,
        skill: {
            name: 'Tidal Wave',
            emoji: '🌊',
            effect: 'dmg',
            power: 50,
            cost: 30,
            description: 'Sóng thần gây 50 sát thương',
        },
        rarity: 'rare',
    },
    sea_serpent: {
        id: 'sea_serpent',
        name: 'Sea Serpent',
        emoji: '🐍',
        type: PET_TYPES.WATER,
        baseHp: 115,
        baseAtk: 27,
        baseDef: 11,
        skill: {
            name: 'Whirlpool',
            emoji: '🌀',
            effect: 'dmg',
            power: 52,
            cost: 30,
            description: 'Xoáy nước gây 52 sát thương',
        },
        rarity: 'epic',
    },
    leviathan: {
        id: 'leviathan',
        name: 'Leviathan',
        emoji: '🐋',
        type: PET_TYPES.WATER,
        baseHp: 140,
        baseAtk: 30,
        baseDef: 13,
        skill: {
            name: 'Ocean Fury',
            emoji: '💙',
            effect: 'dmg',
            power: 65,
            cost: 30,
            description: 'Cơn thịnh nộ đại dương gây 65 sát thương',
        },
        rarity: 'legendary',
    },

    // Air Pets
    wind_spirit: {
        id: 'wind_spirit',
        name: 'Wind Spirit',
        emoji: '💨',
        image: 'assets/pets/wind_hawk.png',
        type: PET_TYPES.AIR,
        baseHp: 75,
        baseAtk: 20,
        baseDef: 8,
        skill: {
            name: 'Gust',
            emoji: '🌬️',
            effect: 'dmg',
            power: 44,
            cost: 30,
            description: 'Cơn gió mạnh gây 44 sát thương',
        },
        rarity: 'uncommon',
    },
    thunder_bird: {
        id: 'thunder_bird',
        name: 'Thunder Bird',
        emoji: '🦅',
        type: PET_TYPES.AIR,
        baseHp: 90,
        baseAtk: 23,
        baseDef: 9,
        skill: {
            name: 'Lightning Strike',
            emoji: '⚡',
            effect: 'dmg',
            power: 50,
            cost: 30,
            description: 'Sét đánh gây 50 sát thương',
        },
        rarity: 'rare',
    },
    storm_drake: {
        id: 'storm_drake',
        name: 'Storm Drake',
        emoji: '🐲',
        type: PET_TYPES.AIR,
        baseHp: 100,
        baseAtk: 26,
        baseDef: 10,
        skill: {
            name: 'Storm Call',
            emoji: '🌩️',
            effect: 'dmg',
            power: 54,
            cost: 30,
            description: 'Triệu hồi bão gây 54 sát thương',
        },
        rarity: 'epic',
    },
    cyclone_giant: {
        id: 'cyclone_giant',
        name: 'Cyclone Giant',
        emoji: '🌪️',
        type: PET_TYPES.AIR,
        baseHp: 120,
        baseAtk: 29,
        baseDef: 11,
        skill: {
            name: 'Tornado',
            emoji: '🌪️',
            effect: 'dmg',
            power: 58,
            cost: 30,
            description: 'Lốc xoáy gây 58 sát thương',
        },
        rarity: 'epic',
    },
    sky_titan: {
        id: 'sky_titan',
        name: 'Sky Titan',
        emoji: '⚡',
        type: PET_TYPES.AIR,
        baseHp: 150,
        baseAtk: 32,
        baseDef: 12,
        skill: {
            name: 'Thunder Strike',
            emoji: '⚡',
            effect: 'dmg',
            power: 70,
            cost: 30,
            description: 'Sấm sét gây 70 sát thương',
        },
        rarity: 'legendary',
    },

    // Light Pets
    star_fox: {
        id: 'star_fox',
        name: 'Star Fox',
        emoji: '🦊',
        image: 'assets/pets/forest_fairy.png',
        type: PET_TYPES.LIGHT,
        baseHp: 80,
        baseAtk: 22,
        baseDef: 9,
        skill: {
            name: 'Star Beam',
            emoji: '⭐',
            effect: 'dmg',
            power: 46,
            cost: 30,
            description: 'Tia sao gây 46 sát thương',
        },
        rarity: 'rare',
    },
    unicorn: {
        id: 'unicorn',
        name: 'Unicorn',
        emoji: '🦄',
        image: 'assets/pets/unicorn.png',
        type: PET_TYPES.LIGHT,
        baseHp: 95,
        baseAtk: 25,
        baseDef: 10,
        skill: {
            name: 'Holy Light',
            emoji: '✨',
            effect: 'healMana',
            power: 35,
            cost: 30,
            description: 'Ánh sáng thánh hồi 35 HP và MP',
        },
        rarity: 'epic',
    },
    griffin: {
        id: 'griffin',
        name: 'Griffin',
        emoji: '🦅',
        type: PET_TYPES.LIGHT,
        baseHp: 105,
        baseAtk: 28,
        baseDef: 11,
        skill: {
            name: 'Sky Strike',
            emoji: '🌟',
            effect: 'dmg',
            power: 56,
            cost: 30,
            description: 'Đòn từ trời gây 56 sát thương',
        },
        rarity: 'epic',
    },
    celestial_dragon: {
        id: 'celestial_dragon',
        name: 'Celestial Dragon',
        emoji: '🐉',
        type: PET_TYPES.LIGHT,
        baseHp: 125,
        baseAtk: 31,
        baseDef: 12,
        skill: {
            name: 'Divine Breath',
            emoji: '💫',
            effect: 'dmg',
            power: 62,
            cost: 30,
            description: 'Hơi thở thần thánh gây 62 sát thương',
        },
        rarity: 'legendary',
    },
    cosmic_entity: {
        id: 'cosmic_entity',
        name: 'Cosmic Entity',
        emoji: '✨',
        type: PET_TYPES.LIGHT,
        baseHp: 160,
        baseAtk: 35,
        baseDef: 15,
        skill: {
            name: 'Cosmic Ray',
            emoji: '🌌',
            effect: 'dmg',
            power: 80,
            cost: 30,
            description: 'Tia vũ trụ gây 80 sát thương',
        },
        rarity: 'legendary',
    },
};

// Rarity colors
const RARITY_COLORS = {
    common: '#9E9E9E',
    uncommon: '#4CAF50',
    rare: '#2196F3',
    epic: '#9C27B0',
    legendary: '#FF9800',
};
